services:
  portfolio-concept-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-concept-website
    ports:
      - "3003:3003"
    restart: unless-stopped
    environment:
      - NODE_ENV=production